INSERT INTO COURSE (UUID, TECHNOLOGY, NAME, LEVEL, PRICE) VALUES (1, 'Back-End', 'Java for beginners', 'B', 30.00);
INSERT INTO COURSE (UUID, TECHNOLOGY, NAME, LEVEL, PRICE) VALUES (2, 'Back-End', 'Java for Intermediate', 'I', 50.00);
INSERT INTO COURSE (UUID, TECHNOLOGY, NAME, LEVEL, PRICE) VALUES (3, 'Front-End', 'Angular 8.0', 'B', 40.00);
INSERT INTO COURSE (UUID, TECHNOLOGY, NAME, LEVEL, PRICE) VALUES (4, 'Dev-Ops', 'A guide to kubernetes', 'B', 50.00);
INSERT INTO COURSE (UUID, TECHNOLOGY, NAME, LEVEL, PRICE) VALUES (5, 'Dev-Ops', 'Learn Docker in 8-days', 'B', 50.00);