INSERT INTO STUDENT (UUID, USER_ID, NAME, EMAIL_ADDRESS) VALUES (1, 'asharma', 'A Sharma', 'a.sharma@gmail.com');

INSERT INTO REGISTER (UUID, STUDENT_ID, COURSE_ID, PREMIUM) VALUES (10, 1, 1, true);
INSERT INTO REGISTER (UUID, STUDENT_ID, COURSE_ID, PREMIUM) VALUES (20, 1, 2, false);
